databases:
  - name: "CaC_24262_Grupo02"
    plan: free

services:
  - type: web
    plan: free
    name: TP-Back-flask-24262-Grupo02
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config src/gconfig.py src.app:app"
    envVars:
      - key: GUNICORN_BIND
        value: "0.0.0.0:8000"
      - key: DB_URL
        fromDatabase:
          name: "CaC_24262_Grupo02"
          property: connectionString